/** @type {Record<string, Array<{title: string, artist: string, year: number, answer: string[]}>>} */
const SONGS = {
  1980: [
    { title: '단발머리', artist: '조용필', year: 1980, answer: ['단발머리'] },
    {
      title: '창밖의 여자',
      artist: '조용필',
      year: 1982,
      answer: ['창밖의여자'],
    },
    { title: '붉은 노을', artist: '이문세', year: 1988, answer: ['붉은노을'] },
    {
      title: '가로수 그늘 아래 서면',
      artist: '이문세',
      year: 1988,
      answer: ['가로수그늘아래서면'],
    },
    {
      title: '홀로 된다는 것',
      artist: '변진섭',
      year: 1988,
      answer: ['홀로된다는것'],
    },
    {
      title: '너에게로 또다시',
      artist: '변진섭',
      year: 1989,
      answer: ['너에게로또다시'],
    },
    {
      title: '리듬 속의 그 춤을',
      artist: '김완선',
      year: 1988,
      answer: ['리듬속의그춤을'],
    },
    {
      title: '어젯밤 이야기',
      artist: '소방차',
      year: 1988,
      answer: ['어젯밤이야기'],
    },
    { title: '희망사항', artist: '변진섭', year: 1989, answer: ['희망사항'] },
    {
      title: '비처럼 음악처럼',
      artist: '김현식',
      year: 1986,
      answer: ['비처럼음악처럼'],
    },
    { title: '남행열차', artist: '김수희', year: 1986, answer: ['남행열차'] },
    {
      title: '사랑하기 때문에',
      artist: '유재하',
      year: 1987,
      answer: ['사랑하기때문에'],
    },
    {
      title: '어쩌다 마주친 그대',
      artist: '송골매',
      year: 1982,
      answer: ['어쩌다마주친그대'],
    },
    { title: '빙글빙글', artist: '나미', year: 1984, answer: ['빙글빙글'] },
    {
      title: 'J에게',
      artist: '이선희',
      year: 1984,
      answer: ['j에게', '제이에게'],
    },
    { title: '그대에게', artist: '신해철', year: 1988, answer: ['그대에게'] },
    {
      title: '매일 그대와',
      artist: '들국화',
      year: 1985,
      answer: ['매일그대와'],
    },
    {
      title: '사랑의 미로',
      artist: '최진희',
      year: 1984,
      answer: ['사랑의미로'],
    },
    {
      title: '내 마음의 보석 상자',
      artist: '해바라기',
      year: 1986,
      answer: ['내마음의보석상자'],
    },
    {
      title: '그것만이 내 세상',
      artist: '들국화',
      year: 1985,
      answer: ['그것만이내세상'],
    },
    {
      title: '광화문 연가',
      artist: '이문세',
      year: 1988,
      answer: ['광화문연가'],
    },
    { title: '담다디', artist: '이상은', year: 1988, answer: ['담다디'] },
    {
      title: '비 오는 날의 수채화',
      artist: '강인원',
      year: 1989,
      answer: ['비오는날의수채화'],
    },
    { title: '모나리자', artist: '조용필', year: 1988, answer: ['모나리자'] },
    {
      title: '킬리만자로의 표범',
      artist: '조용필',
      year: 1985,
      answer: ['킬리만자로의표범'],
    },
    {
      title: '바람 바람 바람',
      artist: '김범룡',
      year: 1985,
      answer: ['바람바람바람'],
    },
    { title: '개똥벌레', artist: '신형원', year: 1987, answer: ['개똥벌레'] },
    {
      title: '미소 속에 비친 그대',
      artist: '신승훈',
      year: 1989,
      answer: ['미소속에비친그대'],
    },
    { title: '꼬마 인형', artist: '최진희', year: 1987, answer: ['꼬마인형'] },
    {
      title: '백만송이 장미',
      artist: '심수봉',
      year: 1988,
      answer: ['백만송이장미'],
    },
  ],
  1990: [
    {
      title: '난 알아요',
      artist: '서태지와 아이들',
      year: 1992,
      answer: ['난알아요'],
    },
    {
      title: '하여가',
      artist: '서태지와 아이들',
      year: 1993,
      answer: ['하여가'],
    },
    { title: '캔디', artist: 'H.O.T', year: 1996, answer: ['캔디', 'candy'] },
    {
      title: '영원한 사랑',
      artist: '핑클',
      year: 1999,
      answer: ['영원한사랑'],
    },
    {
      title: "I'm Your Girl",
      artist: 'S.E.S',
      year: 1997,
      answer: ['imyourgirl', '아임유어걸'],
    },
    {
      title: '보이지 않는 사랑',
      artist: '신승훈',
      year: 1991,
      answer: ['보이지않는사랑'],
    },
    {
      title: '잘못된 만남',
      artist: '김건모',
      year: 1995,
      answer: ['잘못된만남'],
    },
    {
      title: '꿍따리 샤바라',
      artist: '클론',
      year: 1996,
      answer: ['꿍따리샤바라'],
    },
    {
      title: '이브의 경고',
      artist: '박미경',
      year: 1995,
      answer: ['이브의경고'],
    },
    {
      title: '버스 안에서',
      artist: '자자',
      year: 1996,
      answer: ['버스안에서'],
    },
    {
      title: '포이즌',
      artist: '엄정화',
      year: 1998,
      answer: ['포이즌', 'poison'],
    },
    {
      title: 'To Heaven',
      artist: '조성모',
      year: 1998,
      answer: ['toheaven', '투헤븐'],
    },
    { title: 'Honey', artist: '박진영', year: 1998, answer: ['honey', '허니'] },
    { title: '순정', artist: '코요태', year: 1998, answer: ['순정'] },
    {
      title: 'Tell Me',
      artist: '지누션',
      year: 1997,
      answer: ['tellme', '텔미'],
    },
    {
      title: '커플',
      artist: '젝스키스',
      year: 1998,
      answer: ['커플', 'couple'],
    },
    {
      title: 'Dreams Come True',
      artist: 'S.E.S',
      year: 1998,
      answer: ['dreamscometrue', '드림즈컴트루'],
    },
    { title: '와', artist: '이정현', year: 1999, answer: ['와'] },
    { title: '말해줘', artist: '지누션', year: 1997, answer: ['말해줘'] },
    {
      title: '그녀와의 이별',
      artist: '김현정',
      year: 1998,
      answer: ['그녀와의이별'],
    },
    { title: '취중진담', artist: '전람회', year: 1996, answer: ['취중진담'] },
    {
      title: '기억의 습작',
      artist: '전람회',
      year: 1994,
      answer: ['기억의습작'],
    },
    {
      title: '슬픈 언약식',
      artist: '김정민',
      year: 1995,
      answer: ['슬픈언약식'],
    },
    { title: '천생연분', artist: '솔리드', year: 1996, answer: ['천생연분'] },
    {
      title: '흥보가 기가 막혀',
      artist: '육각수',
      year: 1995,
      answer: ['흥보가기가막혀'],
    },
    { title: '행복', artist: 'H.O.T', year: 1997, answer: ['행복'] },
    {
      title: '날개 잃은 천사',
      artist: '룰라',
      year: 1995,
      answer: ['날개잃은천사'],
    },
    { title: '루비', artist: '핑클', year: 1998, answer: ['루비'] },
    {
      title: '상상 속의 너',
      artist: '노이즈',
      year: 1995,
      answer: ['상상속의너'],
    },
    {
      title: '이미 슬픈 사랑',
      artist: '야다',
      year: 1999,
      answer: ['이미슬픈사랑'],
    },
  ],
  2000: [
    {
      title: 'I Believe',
      artist: '신승훈',
      year: 2000,
      answer: ['ibelieve', '아이빌리브'],
    },
    { title: '거짓말', artist: 'g.o.d', year: 2000, answer: ['거짓말'] },
    { title: '성인식', artist: '박지윤', year: 2000, answer: ['성인식'] },
    { title: '너를 위해', artist: '임재범', year: 2000, answer: ['너를위해'] },
    {
      title: '사랑해 그리고 기억해',
      artist: 'g.o.d',
      year: 2000,
      answer: ['사랑해그리고기억해'],
    },
    {
      title: '벌써 일년',
      artist: '브라운 아이즈',
      year: 2001,
      answer: ['벌써일년'],
    },
    { title: '좋은 사람', artist: '토이', year: 2001, answer: ['좋은사람'] },
    { title: '길', artist: 'g.o.d', year: 2001, answer: ['길'] },
    {
      title: 'Never Ending Story',
      artist: '부활',
      year: 2002,
      answer: ['neverendingstory', '네버엔딩스토리'],
    },
    { title: 'No.1', artist: '보아', year: 2002, answer: ['no1', '넘버원'] },
    { title: '보고 싶다', artist: '김범수', year: 2002, answer: ['보고싶다'] },
    {
      title: 'Champion',
      artist: '싸이',
      year: 2002,
      answer: ['champion', '챔피언'],
    },
    {
      title: '낭만 고양이',
      artist: '체리필터',
      year: 2002,
      answer: ['낭만고양이'],
    },
    {
      title: '10 Minutes',
      artist: '이효리',
      year: 2003,
      answer: ['10minutes', '텐미닛'],
    },
    { title: '체념', artist: '빅마마', year: 2003, answer: ['체념'] },
    {
      title: 'Missing You',
      artist: '플라이 투 더 스카이',
      year: 2003,
      answer: ['missingyou', '미싱유'],
    },
    { title: '고백', artist: '델리스파이스', year: 2003, answer: ['고백'] },
    { title: '희재', artist: '성시경', year: 2003, answer: ['희재'] },
    {
      title: 'With Me',
      artist: '휘성',
      year: 2003,
      answer: ['withme', '위드미'],
    },
    { title: '한 남자', artist: '김종국', year: 2004, answer: ['한남자'] },
    { title: 'Hug', artist: '동방신기', year: 2004, answer: ['hug', '허그'] },
    {
      title: '내 여자라니까',
      artist: '이승기',
      year: 2004,
      answer: ['내여자라니까'],
    },
    { title: '눈의 꽃', artist: '박효신', year: 2004, answer: ['눈의꽃'] },
    {
      title: 'Brand New',
      artist: '신화',
      year: 2004,
      answer: ['brandnew', '브랜드뉴'],
    },
    {
      title: 'Timeless',
      artist: 'SG워너비',
      year: 2004,
      answer: ['timeless', '타임리스'],
    },
    { title: '어머나', artist: '장윤정', year: 2004, answer: ['어머나'] },
    {
      title: '사랑은 언제나 목마르다',
      artist: '유미',
      year: 2002,
      answer: ['사랑은언제나목마르다'],
    },
    { title: '친구', artist: '안재욱', year: 2003, answer: ['친구'] },
    {
      title: '사진을 보다가',
      artist: '바이브',
      year: 2003,
      answer: ['사진을보다가'],
    },
    { title: '가거라', artist: '왁스', year: 2001, answer: ['가거라'] },
  ],
  2005: [
    { title: '가시', artist: '버즈', year: 2005, answer: ['가시'] },
    { title: '응급실', artist: 'izi', year: 2005, answer: ['응급실'] },
    { title: '겁쟁이', artist: '버즈', year: 2005, answer: ['겁쟁이'] },
    {
      title: '사랑했나봐',
      artist: '윤도현',
      year: 2005,
      answer: ['사랑했나봐'],
    },
    {
      title: '애인 있어요',
      artist: '이은미',
      year: 2005,
      answer: ['애인있어요'],
    },
    { title: '내사람', artist: 'SG워너비', year: 2006, answer: ['내사람'] },
    {
      title: '몽환의 숲',
      artist: '키네틱 플로우',
      year: 2006,
      answer: ['몽환의숲'],
    },
    {
      title: '비밀번호 486',
      artist: '윤하',
      year: 2007,
      answer: ['비밀번호486'],
    },
    { title: '거짓말', artist: '빅뱅', year: 2007, answer: ['거짓말'] },
    {
      title: 'Tell Me',
      artist: '원더걸스',
      year: 2007,
      answer: ['tellme', '텔미'],
    },
    { title: '미인', artist: '이기찬', year: 2007, answer: ['미인'] },
    { title: '하루하루', artist: '빅뱅', year: 2008, answer: ['하루하루'] },
    {
      title: 'Mirotic',
      artist: '동방신기',
      year: 2008,
      answer: ['mirotic', '미로틱'],
    },
    {
      title: 'Nobody',
      artist: '원더걸스',
      year: 2008,
      answer: ['nobody', '노바디'],
    },
    {
      title: 'U-Go-Girl',
      artist: '이효리',
      year: 2008,
      answer: ['ugogirl', '유고걸'],
    },
    {
      title: 'Love119',
      artist: '케이윌',
      year: 2008,
      answer: ['love119', '러브119'],
    },
    { title: 'Gee', artist: '소녀시대', year: 2009, answer: ['gee', '지'] },
    {
      title: 'Sorry, Sorry',
      artist: '슈퍼주니어',
      year: 2009,
      answer: ['sorrysorry', '쏘리쏘리'],
    },
    {
      title: 'Abracadabra',
      artist: '브라운 아이드 걸스',
      year: 2009,
      answer: ['abracadabra', '아브라카다브라'],
    },
    {
      title: 'Heartbreaker',
      artist: '지드래곤',
      year: 2009,
      answer: ['heartbreaker', '하트브레이커'],
    },
    {
      title: 'Ring Ding Dong',
      artist: '샤이니',
      year: 2009,
      answer: ['ringdingdong', '링딩동'],
    },
    { title: 'Fire', artist: '2NE1', year: 2009, answer: ['fire', '파이어'] },
    {
      title: "I Don't Care",
      artist: '2NE1',
      year: 2009,
      answer: ['idontcare', '아이돈케어'],
    },
    { title: '8282', artist: '다비치', year: 2009, answer: ['8282'] },
    {
      title: 'Hot Issue',
      artist: '포미닛',
      year: 2009,
      answer: ['hotissue', '핫이슈'],
    },
    { title: '외톨이야', artist: '씨엔블루', year: 2009, answer: ['외톨이야'] },
    {
      title: 'Again & Again',
      artist: '2PM',
      year: 2009,
      answer: ['againandagain', '어게인앤어게인'],
    },
    {
      title: 'Mister',
      artist: '카라',
      year: 2009,
      answer: ['mister', '미스터'],
    },
    {
      title: 'Replay (누난 너무 예뻐)',
      artist: '샤이니',
      year: 2008,
      answer: ['누난너무예뻐', 'replay', '리플레이'],
    },
    {
      title: '소원을 말해봐 (Genie)',
      artist: '소녀시대',
      year: 2009,
      answer: ['소원을말해봐', 'genie', '지니'],
    },
  ],
  2010: [
    { title: '좋은 날', artist: '아이유', year: 2010, answer: ['좋은날'] },
    {
      title: 'Bad Girl Good Girl',
      artist: 'miss A',
      year: 2010,
      answer: ['badgirlgoodgirl', '배드걸굿걸'],
    },
    {
      title: '루시퍼 (Lucifer)',
      artist: '샤이니',
      year: 2010,
      answer: ['lucifer', '루시퍼'],
    },
    {
      title: '훗 (Hoot)',
      artist: '소녀시대',
      year: 2010,
      answer: ['hoot', '훗'],
    },
    {
      title: '미인아 (Bonamana)',
      artist: '슈퍼주니어',
      year: 2010,
      answer: ['미인아', 'bonamana', '보나마나'],
    },
    {
      title: '내가 제일 잘 나가',
      artist: '2NE1',
      year: 2011,
      answer: ['내가제일잘나가', 'iamthebest'],
    },
    {
      title: 'Roly-Poly',
      artist: '티아라',
      year: 2011,
      answer: ['rolypoly', '롤리폴리'],
    },
    {
      title: 'Fiction',
      artist: '비스트',
      year: 2011,
      answer: ['fiction', '픽션'],
    },
    {
      title: '압구정 날라리',
      artist: '처진 달팽이',
      year: 2011,
      answer: ['압구정날라리'],
    },
    {
      title: '강남스타일',
      artist: '싸이',
      year: 2012,
      answer: ['강남스타일', 'gangnamstyle'],
    },
    {
      title: '나혼자 (Alone)',
      artist: '씨스타',
      year: 2012,
      answer: ['나혼자', 'alone'],
    },
    {
      title: 'Fantastic Baby',
      artist: '빅뱅',
      year: 2012,
      answer: ['fantasticbaby', '판타스틱베이비'],
    },
    {
      title: '벚꽃 엔딩',
      artist: '버스커 버스커',
      year: 2012,
      answer: ['벚꽃엔딩'],
    },
    {
      title: '1,2,3,4',
      artist: '이하이',
      year: 2012,
      answer: ['1234', '원투쓰리포'],
    },
    {
      title: '으르렁 (Growl)',
      artist: 'EXO',
      year: 2013,
      answer: ['으르렁', 'growl'],
    },
    { title: '빠빠빠', artist: '크레용팝', year: 2013, answer: ['빠빠빠'] },
    {
      title: 'NoNoNo',
      artist: '에이핑크',
      year: 2013,
      answer: ['nonono', '노노노'],
    },
    {
      title: '이름이 뭐예요?',
      artist: '4minute',
      year: 2013,
      answer: ['이름이뭐예요'],
    },
    {
      title: '위아래',
      artist: 'EXID',
      year: 2014,
      answer: ['위아래', 'upanddown'],
    },
    {
      title: '썸 (Some)',
      artist: '소유X정기고',
      year: 2014,
      answer: ['썸', 'some'],
    },
    {
      title: 'Mr. Chu',
      artist: '에이핑크',
      year: 2014,
      answer: ['mrchu', '미스터츄'],
    },
    { title: '야생화', artist: '박효신', year: 2014, answer: ['야생화'] },
    {
      title: '공허해',
      artist: '위너',
      year: 2014,
      answer: ['공허해', 'empty'],
    },
    {
      title: '금요일에 만나요',
      artist: '아이유',
      year: 2013,
      answer: ['금요일에만나요'],
    },
    { title: 'Blue', artist: '빅뱅', year: 2012, answer: ['blue', '블루'] },
    { title: '기대해', artist: '걸스데이', year: 2013, answer: ['기대해'] },
    {
      title: 'Touch My Body',
      artist: '씨스타',
      year: 2014,
      answer: ['touchmybody', '터치마이바디'],
    },
    { title: 'LUV', artist: '에이핑크', year: 2014, answer: ['luv', '러브'] },
    {
      title: 'High High',
      artist: 'GD&TOP',
      year: 2010,
      answer: ['highhigh', '하이하이'],
    },
    {
      title: 'I Need A Girl',
      artist: '태양',
      year: 2010,
      answer: ['ineedagirl', '아이니드어걸'],
    },
  ],
  2015: [
    {
      title: '오늘부터 우리는 (Me Gustas Tu)',
      artist: '여자친구',
      year: 2015,
      answer: ['오늘부터우리는', 'megustastu'],
    },
    {
      title: '뱅뱅뱅 (BANG BANG BANG)',
      artist: '빅뱅',
      year: 2015,
      answer: ['뱅뱅뱅', 'bangbangbang'],
    },
    {
      title: 'Dumb Dumb',
      artist: '레드벨벳',
      year: 2015,
      answer: ['dumbdumb', '덤덤'],
    },
    {
      title: 'OOH-AHH하게',
      artist: 'TWICE',
      year: 2015,
      answer: ['우아하게', 'oohahh하게'],
    },
    {
      title: '아예 (Ah Yeah)',
      artist: 'EXID',
      year: 2015,
      answer: ['아예', 'ahyeah'],
    },
    {
      title: 'CHEER UP',
      artist: 'TWICE',
      year: 2016,
      answer: ['cheerup', '치어업'],
    },
    {
      title: '시간을 달려서 (Rough)',
      artist: '여자친구',
      year: 2016,
      answer: ['시간을달려서', 'rough'],
    },
    {
      title: '피 땀 눈물',
      artist: 'BTS',
      year: 2016,
      answer: ['피땀눈물', 'bloodsweatandtears'],
    },
    {
      title: '우주를 줄게',
      artist: '볼빨간사춘기',
      year: 2016,
      answer: ['우주를줄게'],
    },
    { title: 'TT', artist: 'TWICE', year: 2016, answer: ['tt', '티티'] },
    { title: 'DNA', artist: 'BTS', year: 2017, answer: ['dna', '디엔에이'] },
    {
      title: '빨간 맛 (Red Flavor)',
      artist: '레드벨벳',
      year: 2017,
      answer: ['빨간맛', 'redflavor'],
    },
    {
      title: '밤편지',
      artist: '아이유',
      year: 2017,
      answer: ['밤편지', 'throughthenight'],
    },
    {
      title: '에너제틱 (Energetic)',
      artist: '워너원',
      year: 2017,
      answer: ['energetic', '에너제틱'],
    },
    {
      title: 'Really Really',
      artist: 'WINNER',
      year: 2017,
      answer: ['reallyreally', '릴리릴리'],
    },
    {
      title: '가시나',
      artist: '선미',
      year: 2017,
      answer: ['gashina', '가시나'],
    },
    {
      title: '사랑을 했다 (LOVE SCENARIO)',
      artist: 'iKON',
      year: 2018,
      answer: ['사랑을했다', 'lovescenario'],
    },
    {
      title: 'DDU-DU DDU-DU',
      artist: '블랙핑크',
      year: 2018,
      answer: ['뚜두뚜두', 'ddududdudu'],
    },
    {
      title: '뿜뿜',
      artist: '모모랜드',
      year: 2018,
      answer: ['뿜뿜', 'bboombboom'],
    },
    {
      title: '여행',
      artist: '볼빨간사춘기',
      year: 2018,
      answer: ['여행', 'travel'],
    },
    { title: 'IDOL', artist: 'BTS', year: 2018, answer: ['idol', '아이돌'] },
    {
      title: '벌써 12시',
      artist: '청하',
      year: 2019,
      answer: ['벌써12시', 'gottago'],
    },
    {
      title: '달라달라 (DALLA DALLA)',
      artist: 'ITZY',
      year: 2019,
      answer: ['달라달라', 'dalladalla'],
    },
    {
      title: '작은 것들을 위한 시 (Boy With Luv)',
      artist: 'BTS',
      year: 2019,
      answer: ['작은것들을위한시', 'boywithluv'],
    },
    {
      title: '안녕 (So Long)',
      artist: '폴킴',
      year: 2019,
      answer: ['안녕', 'solong'],
    },
    {
      title: '주저하는 연인들을 위해',
      artist: '잔나비',
      year: 2019,
      answer: ['주저하는연인들을위해'],
    },
    {
      title: 'Psycho',
      artist: '레드벨벳',
      year: 2019,
      answer: ['psycho', '사이코'],
    },
    { title: 'FANCY', artist: 'TWICE', year: 2019, answer: ['fancy', '팬시'] },
    {
      title: '휘파람',
      artist: '블랙핑크',
      year: 2016,
      answer: ['휘파람', 'whistle'],
    },
    {
      title: '불타오르네 (FIRE)',
      artist: 'BTS',
      year: 2016,
      answer: ['불타오르네', 'fire'],
    },
  ],
  2021: [
    { title: 'Butter', artist: 'BTS', year: 2021, answer: ['butter', '버터'] },
    {
      title: 'Next Level',
      artist: 'aespa',
      year: 2021,
      answer: ['nextlevel', '넥스트레벨'],
    },
    {
      title: 'ELEVEN',
      artist: 'IVE',
      year: 2021,
      answer: ['eleven', '일레븐'],
    },
    { title: 'ASAP', artist: 'STAYC', year: 2021, answer: ['asap', '에이셉'] },
    {
      title: 'Celebrity',
      artist: '아이유',
      year: 2021,
      answer: ['celebrity', '셀러브리티'],
    },
    {
      title: 'Permission to Dance',
      artist: 'BTS',
      year: 2021,
      answer: ['permissiontodance', '퍼미션투댄스'],
    },
    {
      title: 'Weekend',
      artist: '태연',
      year: 2021,
      answer: ['weekend', '위켄드'],
    },
    { title: '신호등', artist: '이무진', year: 2021, answer: ['신호등'] },
    {
      title: 'Savage',
      artist: 'aespa',
      year: 2021,
      answer: ['savage', '새비지'],
    },
    {
      title: '라일락',
      artist: '아이유',
      year: 2021,
      answer: ['라일락', 'lilac'],
    },
    {
      title: 'Dun Dun Dance',
      artist: '오마이걸',
      year: 2021,
      answer: ['dundundance', '던던댄스'],
    },
    { title: '헤픈 우연', artist: '헤이즈', year: 2021, answer: ['헤픈우연'] },
    {
      title: '바라만 본다',
      artist: 'MSG워너비',
      year: 2021,
      answer: ['바라만본다'],
    },
    {
      title: 'Alcohol-Free',
      artist: 'TWICE',
      year: 2021,
      answer: ['alcoholfree', '알콜프리'],
    },
    { title: '안녕', artist: '조이', year: 2021, answer: ['안녕', 'hello'] },
    {
      title: '치맛바람',
      artist: '브레이브걸스',
      year: 2021,
      answer: ['치맛바람'],
    },
    { title: 'LOCO', artist: 'ITZY', year: 2021, answer: ['loco', '로코'] },
    {
      title: 'Queendom',
      artist: '레드벨벳',
      year: 2021,
      answer: ['queendom', '퀸덤'],
    },
    {
      title: 'Rock with you',
      artist: '세븐틴',
      year: 2021,
      answer: ['rockwithyou', '락위드유'],
    },
    {
      title: 'Strawberry Moon',
      artist: '아이유',
      year: 2021,
      answer: ['strawberrymoon', '스트로베리문'],
    },
    {
      title: 'DUMB DUMB',
      artist: '전소미',
      year: 2021,
      answer: ['dumbdumb', '덤덤'],
    },
    { title: '비와 당신', artist: '이무진', year: 2021, answer: ['비와당신'] },
    {
      title: '소리꾼',
      artist: 'Stray Kids',
      year: 2021,
      answer: ['소리꾼', 'thunderous'],
    },
    {
      title: 'First',
      artist: '에버글로우',
      year: 2021,
      answer: ['first', '퍼스트'],
    },
    {
      title: 'Hey Mama',
      artist: 'WayB',
      year: 2021,
      answer: ['heymama', '헤이마마'],
    },
    {
      title: '색안경',
      artist: 'STAYC',
      year: 2021,
      answer: ['색안경', 'stereotypes'],
    },
    {
      title: 'Cold Blooded',
      artist: '제시',
      year: 2021,
      answer: ['coldblooded', '콜드블러드'],
    },
    {
      title: 'LALISA',
      artist: '리사',
      year: 2021,
      answer: ['lalisa', '라리사'],
    },
    {
      title: 'Bad Habits',
      artist: 'Shaun',
      year: 2021,
      answer: ['badhabits', '배드해빗'],
    },
    {
      title: 'Traffic Light',
      artist: '이무진',
      year: 2021,
      answer: ['신호등', 'trafficlight'],
    },
  ],
  2022: [
    {
      title: 'LOVE DIVE',
      artist: 'IVE',
      year: 2022,
      answer: ['lovedive', '러브다이브'],
    },
    {
      title: 'Attention',
      artist: 'NewJeans',
      year: 2022,
      answer: ['attention', '어텐션'],
    },
    {
      title: 'FEARLESS',
      artist: '르세라핌',
      year: 2022,
      answer: ['fearless', '피어리스'],
    },
    {
      title: 'After LIKE',
      artist: 'IVE',
      year: 2022,
      answer: ['afterlike', '애프터라이크'],
    },
    {
      title: 'TOMBOY',
      artist: '(여자)아이들',
      year: 2022,
      answer: ['tomboy', '톰보이'],
    },
    {
      title: 'Hype Boy',
      artist: 'NewJeans',
      year: 2022,
      answer: ['hypeboy', '하입보이'],
    },
    {
      title: 'Antifragile',
      artist: '르세라핌',
      year: 2022,
      answer: ['antifragile', '안티프래자일'],
    },
    {
      title: '사건의 지평선',
      artist: '윤하',
      year: 2022,
      answer: ['사건의지평선'],
    },
    {
      title: 'Pink Venom',
      artist: '블랙핑크',
      year: 2022,
      answer: ['pinkvenom', '핑크베놈'],
    },
    {
      title: 'Shut Down',
      artist: '블랙핑크',
      year: 2022,
      answer: ['shutdown', '셧다운'],
    },
    {
      title: 'INVU',
      artist: '태연',
      year: 2022,
      answer: ['invu', '아이엔뷔유'],
    },
    { title: 'Dice', artist: 'NMIXX', year: 2022, answer: ['dice', '다이스'] },
    {
      title: 'Feel My Rhythm',
      artist: '레드벨벳',
      year: 2022,
      answer: ['feelmyrhythm', '필마이리듬'],
    },
    {
      title: 'SMILEY',
      artist: '최예나',
      year: 2022,
      answer: ['smiley', '스마일리'],
    },
    { title: 'POP!', artist: '나연', year: 2022, answer: ['pop', '팝'] },
    { title: '나의 X에게', artist: '경서', year: 2022, answer: ['나의x에게'] },
    {
      title: '그때 그 순간 그대로',
      artist: 'WSG워너비',
      year: 2022,
      answer: ['그때그순간그대로'],
    },
    {
      title: '정이라고 하자',
      artist: '빅나티',
      year: 2022,
      answer: ['정이라고하자'],
    },
    {
      title: 'Sneakers',
      artist: 'ITZY',
      year: 2022,
      answer: ['sneakers', '스니커즈'],
    },
    {
      title: 'MANIAC',
      artist: 'Stray Kids',
      year: 2022,
      answer: ['maniac', '매니악'],
    },
    {
      title: 'Case 143',
      artist: 'Stray Kids',
      year: 2022,
      answer: ['case143', '케이스143'],
    },
    {
      title: 'Cookie',
      artist: 'NewJeans',
      year: 2022,
      answer: ['cookie', '쿠키'],
    },
    {
      title: 'The Astronaut',
      artist: '진',
      year: 2022,
      answer: ['theastronaut', '디아스트로넛'],
    },
    {
      title: 'Wild Flower',
      artist: 'RM',
      year: 2022,
      answer: ['wildflower', '들꽃놀이'],
    },
    {
      title: 'Nxde',
      artist: '(여자)아이들',
      year: 2022,
      answer: ['nxde', '누드'],
    },
    {
      title: '도깨비불',
      artist: 'aespa',
      year: 2022,
      answer: ['도깨비불', 'illusion'],
    },
    { title: 'Girls', artist: 'aespa', year: 2022, answer: ['girls', '걸스'] },
    {
      title: 'Glitch Mode',
      artist: 'NCT DREAM',
      year: 2022,
      answer: ['glitchmode', '글리치모드'],
    },
    {
      title: 'Candy',
      artist: 'NCT DREAM',
      year: 2022,
      answer: ['candy', '캔디'],
    },
    {
      title: 'Run BTS',
      artist: 'BTS',
      year: 2022,
      answer: ['runbts', '달려라방탄'],
    },
  ],
  2023: [
    {
      title: 'Ditto',
      artist: 'NewJeans',
      year: 2023,
      answer: ['ditto', '디토'],
    },
    { title: 'I AM', artist: 'IVE', year: 2023, answer: ['iam', '아이엠'] },
    { title: 'Seven', artist: '정국', year: 2023, answer: ['seven', '세븐'] },
    {
      title: 'Super Shy',
      artist: 'NewJeans',
      year: 2023,
      answer: ['supershy', '슈퍼샤이'],
    },
    {
      title: 'Queencard',
      artist: '(여자)아이들',
      year: 2023,
      answer: ['queencard', '퀸카'],
    },
    {
      title: 'Spicy',
      artist: 'aespa',
      year: 2023,
      answer: ['spicy', '스파이시'],
    },
    {
      title: 'Love Lee',
      artist: 'AKMU',
      year: 2023,
      answer: ['lovelee', '러브리'],
    },
    { title: 'OMG', artist: 'NewJeans', year: 2023, answer: ['omg', '오엠지'] },
    {
      title: 'UNFORGIVEN',
      artist: '르세라핌',
      year: 2023,
      answer: ['unforgiven', '언포기븐'],
    },
    {
      title: 'Fast Forward',
      artist: '전소미',
      year: 2023,
      answer: ['fastforward', '패스트포워드'],
    },
    { title: 'Baddie', artist: 'IVE', year: 2023, answer: ['baddie', '배디'] },
    { title: 'Kitsch', artist: 'IVE', year: 2023, answer: ['kitsch', '키치'] },
    {
      title: '손오공',
      artist: '세븐틴',
      year: 2023,
      answer: ['손오공', 'super'],
    },
    {
      title: '이브, 프시케 그리고 푸른 수염의 아내',
      artist: '르세라핌',
      year: 2023,
      answer: ['이프푸', '이브프시케그리고푸른수염의아내'],
    },
    { title: '꽃', artist: '지수', year: 2023, answer: ['꽃', 'flower'] },
    {
      title: 'Teddy Bear',
      artist: 'STAYC',
      year: 2023,
      answer: ['teddybear', '테디베어'],
    },
    {
      title: '건물 사이에 피어난 장미',
      artist: 'H1-KEY',
      year: 2023,
      answer: ['건물사이에피어난장미', '건사피장'],
    },
    {
      title: 'Cupid',
      artist: 'FIFTY FIFTY',
      year: 2023,
      answer: ['cupid', '큐피드'],
    },
    {
      title: 'Get A Guitar',
      artist: 'RIIZE',
      year: 2023,
      answer: ['getaguitar', '겟어기타'],
    },
    {
      title: 'Perfect Night',
      artist: '르세라핌',
      year: 2023,
      answer: ['perfectnight', '퍼펙트나이트'],
    },
    {
      title: 'Drama',
      artist: 'aespa',
      year: 2023,
      answer: ['drama', '드라마'],
    },
    { title: 'To. X', artist: '태연', year: 2023, answer: ['tox', '투엑스'] },
    {
      title: '파이팅해야지',
      artist: '부석순',
      year: 2023,
      answer: ['파이팅해야지', 'fighting'],
    },
    {
      title: 'Either Way',
      artist: 'IVE',
      year: 2023,
      answer: ['eitherway', '이더웨이'],
    },
    {
      title: 'Cool With You',
      artist: 'NewJeans',
      year: 2023,
      answer: ['coolwithyou', '쿨위드유'],
    },
    {
      title: 'ETA',
      artist: 'NewJeans',
      year: 2023,
      answer: ['eta', '이티에이'],
    },
    {
      title: 'S-Class',
      artist: 'Stray Kids',
      year: 2023,
      answer: ['sclass', '특', '에스클래스'],
    },
    {
      title: 'Fact Check',
      artist: 'NCT 128',
      year: 2023,
      answer: ['factcheck', '팩트체크'],
    },
    {
      title: 'Bite Me',
      artist: 'ENHYPEN',
      year: 2023,
      answer: ['biteme', '바이트미'],
    },
    { title: '3D', artist: '정국', year: 2023, answer: ['3d', '쓰리디'] },
  ],
  2024: [
    {
      title: 'Magnetic',
      artist: 'ILLIT',
      year: 2024,
      answer: ['magnetic', '마그네틱'],
    },
    {
      title: 'Supernova',
      artist: 'aespa',
      year: 2024,
      answer: ['supernova', '슈퍼노바'],
    },
    {
      title: 'Bam Yang Gang',
      artist: '비비',
      year: 2024,
      answer: ['bamyanggang', '밤양갱'],
    },
    {
      title: 'How Sweet',
      artist: 'NewJeans',
      year: 2024,
      answer: ['howsweet', '하우스위트'],
    },
    {
      title: 'Armageddon',
      artist: 'aespa',
      year: 2024,
      answer: ['armageddon', '아마겟돈'],
    },
    {
      title: 'APT.',
      artist: '로제 & Bruno Mars',
      year: 2024,
      answer: ['apt', '아파트'],
    },
    {
      title: 'Plot Twist',
      artist: 'TWS',
      year: 2024,
      answer: ['plottwist', '첫만남은계획대로되지않아'],
    },
    {
      title: 'Mantra',
      artist: 'JENNIE',
      year: 2024,
      answer: ['mantra', '만트라'],
    },
    {
      title: 'Smart',
      artist: '르세라핌',
      year: 2024,
      answer: ['smart', '스마트'],
    },
    {
      title: 'Sticky',
      artist: 'KISS OF LIFE',
      year: 2024,
      answer: ['sticky', '스티키'],
    },
    { title: 'SPOT!', artist: '지코', year: 2024, answer: ['spot', '스팟'] },
    {
      title: 'Welcome to the Show',
      artist: 'DAY6',
      year: 2024,
      answer: ['welcometotheshow', '웰컴투더쇼'],
    },
    {
      title: 'Shooting Star',
      artist: 'Kep1er',
      year: 2024,
      answer: ['shootingstar', '슈팅스타'],
    },
    {
      title: 'Sheesh',
      artist: 'BABYMONSTER',
      year: 2024,
      answer: ['sheesh', '쉬쉬'],
    },
    {
      title: 'Love wins all',
      artist: '아이유',
      year: 2024,
      answer: ['lovewinsall', '러브윈즈올'],
    },
    { title: '홀씨', artist: '아이유', year: 2024, answer: ['홀씨', 'holssi'] },
    { title: 'Easy', artist: '르세라핌', year: 2024, answer: ['easy', '이지'] },
    {
      title: 'Midas Touch',
      artist: 'KISS OF LIFE',
      year: 2024,
      answer: ['midastouch', '마이다스터치'],
    },
    { title: 'Heya', artist: 'IVE', year: 2024, answer: ['heya', '해야'] },
    {
      title: 'Accendio',
      artist: 'IVE',
      year: 2024,
      answer: ['accendio', '아센디오'],
    },
    {
      title: 'Supernatural',
      artist: 'NewJeans',
      year: 2024,
      answer: ['supernatural', '슈퍼내추럴'],
    },
    {
      title: 'Bubble Gum',
      artist: 'NewJeans',
      year: 2024,
      answer: ['bubblegum', '버블검'],
    },
    {
      title: 'ABCD',
      artist: '나연',
      year: 2024,
      answer: ['abcd', '에이비씨디'],
    },
    {
      title: 'Boom Boom Bass',
      artist: 'RIIZE',
      year: 2024,
      answer: ['boomboombass', '붐붐베이스'],
    },
    {
      title: 'Walk',
      artist: 'NCT 127',
      year: 2024,
      answer: ['walk', '삐그덕'],
    },
    {
      title: 'Chk Chk Boom',
      artist: 'Stray Kids',
      year: 2024,
      answer: ['chkchkboom', '칙칙붐'],
    },
    {
      title: 'K-POP',
      artist: '지드래곤',
      year: 2024,
      answer: ['kpop', '케이팝'],
    },
    {
      title: 'POWER',
      artist: '지드래곤',
      year: 2024,
      answer: ['power', '파워'],
    },
    {
      title: 'Live My Life',
      artist: 'aespa',
      year: 2024,
      answer: ['livemylife', '리브마이라이프'],
    },
    {
      title: 'Moonlight',
      artist: '태연',
      year: 2024,
      answer: ['moonlight', '문라이트'],
    },
  ],
  2025: [
    {
      title: 'Supernatural',
      artist: 'NewJeans',
      year: 2025,
      answer: ['supernatural', '슈퍼내추럴'],
    },
    {
      title: 'Crazy',
      artist: 'LE SSERAFIM',
      year: 2025,
      answer: ['crazy', '크레이지'],
    },
    {
      title: 'Lucky Girl Syndrome',
      artist: 'ILLIT',
      year: 2025,
      answer: ['luckygirlsyndrome', '럭키걸신드롬'],
    },
    {
      title: '별별별',
      artist: '아이유',
      year: 2025,
      answer: ['별별별', 'starstarstar'],
    },
    {
      title: 'Born Pink',
      artist: '블랙핑크',
      year: 2025,
      answer: ['bornpink', '본핑크'],
    },
    {
      title: 'Whiplash',
      artist: 'aespa',
      year: 2024,
      answer: ['whiplash', '위플래쉬'],
    }, // 24년말 인기곡 보충
    { title: 'Gold', artist: 'ITZY', year: 2024, answer: ['gold', '골드'] },
    {
      title: 'Cherish',
      artist: 'ILLIT',
      year: 2024,
      answer: ['cherish', '체리시'],
    },
    {
      title: 'Call Me Any Time',
      artist: '지코',
      year: 2025,
      answer: ['callmeanytime', '콜미애니타임'],
    },
    {
      title: 'Forever',
      artist: 'BABYMONSTER',
      year: 2024,
      answer: ['forever', '포에버'],
    },
    {
      title: 'DRIP',
      artist: 'BABYMONSTER',
      year: 2024,
      answer: ['drip', '드립'],
    },
    {
      title: 'CLIK CLAK',
      artist: 'BABYMONSTER',
      year: 2024,
      answer: ['clikclak', '클릭클랙'],
    },
    // (이하 2025년 곡들은 2024년 말~2025년 초 기준으로 리스트업 됨)
  ],
};

function getSongsForDecades(decades) {
  const result = [];
  for (const decade of decades) {
    const songs = SONGS[decade] ?? [];
    for (const song of songs) {
      result.push({ ...song, decade });
    }
  }
  return result;
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

module.exports = { SONGS, getSongsForDecades, shuffle };
